### ISSUE TITLE
转载到Greasy Fork

### ISSUE THREAD

**Issue by skydog221** [FurryR/hyren#1]
你好！凌老师！
我想把这个脚本转载到Greasy Fork用户脚本大全里，会标明原作者，请问您是否同意？
这会方便一些不能访问github/不会使用github action的用户
谢谢！

**Comment by FurryR** [comment]
啊可是我自己有 GreasyFork 账户）））

**Comment by FurryR** [comment]
GreasyFork 放不下这个脚本。

**Comment by skydog221** [comment]
> GreasyFork 放不下这个脚本。

哦哦
